#! /bin/bash

echo "Calamar\t"
echo "Foca\t"
echo "Delfín\n"
echo "Pez león\t"
echo "León Marino\t"
echo "Cachalote\n"
echo "Ballena franca\t"
echo "Ballena azul\t"
echo "Anguila eléctrica\n"
echo "Medusa\t"
echo "Tiburón ballena\t"
echo "Sardinas\n"
echo "Manatí\t"
echo "Trucha común\t"
echo "Pulpo\n"
echo "Caracol de mar\t"
echo "Pez luna\t"
echo "Tiburón blanco\n"
echo "Carpas\t"
echo "Pez espada\t"
echo "Tortuga marina\n"
echo "Pez globo\t"
echo "Langosta\t"
echo "Atún\n"
echo "Salmón\t"
echo "Almeja\t"
echo "Coral\n"
echo "Mojarrita\t"
echo "Piraña\t"
echo "Marsopa\n"
echo "Pingüino\t"
echo "Bacalao\t"
echo "Caballito de mar\n"
echo "Mejillón\t"
echo "Estrella de mar\t"
echo "Orca\n"
echo "Erizo de mar\t"
echo "Surubí"
